### ISSUE TITLE
窄屏显示页面时，地图上的年份导航按钮点击区域会出现偏倚。

### ISSUE THREAD

**Issue by VintLin** [yihong0618/running_page#415]
## 问题描述
窄屏显示页面时，地图上的年份导航按钮点击区域会出现偏倚。

## 如何复现
以[yihong0618](https://yihong.run/)为例，在移动设备上打开该页面。年份导航按钮的点击区域会往前偏倚，此时点击**2023**的**前半部分**（也就是下图所示的红框区域）可以导航到**2023**，但是点击到**2023**的**后半部分**则会导航到**2022**。
![Xnip2023-05-11_09-12-32](https://github.com/yihong0618/running_page/assets/26142850/334aee8c-4d37-4b25-b5c7-88c5f12795ed)

## 我的解决方法
修改 **<项目目录>/src/components/RunMap/style.module.scss**中的button配置，去除width，修改padding。
### 修改前：
```css
.button {
  display: inline-block;
  position: relative;
  cursor: pointer;
  width: 7%;
  padding: 1.3rem;
  margin-top: 0.1rem;
  font-size: 1rem;
  text-align: center;
  color: white;
  font-family: $global-font-family;
}
```

### 修改后：
```css
.button {
  display: inline-block;
  position: relative;
  cursor: pointer;
  padding: 1.3rem 0.4rem;
  margin-top: 0.1rem;
  font-size: 1rem;
  text-align: center;
  color: white;
  font-family: $global-font-family;
}
```
