### ISSUE TITLE
workflow  run_data_sync -->  Error: You have to provide a GITHUB_TOKEN or GH_PAT

### ISSUE THREAD

**Issue by coolp4n** [yihong0618/running_page#489]
hi yihong 感谢您的项目 作为一个几年的跑者 第一次看到这个 觉得太酷辣！
目前遇到的问题是 当悦跑圈自动同步时的第二个workflow 会显示GitHub_token 不存在 
但是单独跑publish github pages时 是可以的  不清楚是啥原因呢？？
我在secrets中有配置token ，变量名换成了ACCESS_TOKEN
我的repo是https://github.com/coolp4n/running_page/actions

**Comment by yihong0618** [comment]
你需要配置个 ACCESS_TOKEN 在 secret 里

**Comment by coolp4n** [comment]
有配置 ACCESS_TOKEN 在 secret 的

**Comment by coolp4n** [comment]
> 你需要配置个 ACCESS_TOKEN 在 secret 里


有配置 ACCESS_TOKEN 在 secret 的

**Comment by yihong0618** [comment]
https://github.com/coolp4n/running_page/blob/059c5e9efb9910ab80c81730d0d5bbae876e0a11/.github/workflows/run_data_sync.yml#L191

在这下面也加上 env
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

**Comment by coolp4n** [comment]
> https://github.com/coolp4n/running_page/blob/059c5e9efb9910ab80c81730d0d5bbae876e0a11/.github/workflows/run_data_sync.yml#L191
> 
> 在这下面也加上 env env: GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

试了 还是不行

**Comment by yihong0618** [comment]
@agassiyzh 
我们看一下。

**Comment by agassiyzh** [comment]
> @agassiyzh
> 我们看一下。

OK

**Comment by agassiyzh** [comment]
github项目里面GITHUB_TOKEN是默认就有的，不需要自己创建。你看一下Settings -> actions-> General里面 `Workflow permissions`有没有给写的权限

<img width="1130" alt="截屏2023-09-13 14 00 48" src="https://github.com/yihong0618/running_page/assets/413855/e4fdc245-d6b7-4209-aea9-da18772bb057">

**Comment by yihong0618** [comment]
@agassiyzh 这个问题好像挺常见，running_page 群里也有遇到的了

**Comment by agassiyzh** [comment]
> > github项目里面GITHUB_TOKEN是默认就有的，不需要自己创建。你看一下Settings -> actions-> General里面 `Workflow permissions`有没有给写的权限
> > <img alt="截屏2023-09-13 14 00 48" width="1130" src="https://user-images.githubusercontent.com/413855/267551451-e4fdc245-d6b7-4209-aea9-da18772bb057.png">
> 
> 我使用的是ACCESS_TOKEN 变量名， 看了设置 是有写权限的 。单独跑publish github pages是可以的 但是在run_data_sync则会有这个报错 ![image](https://user-images.githubusercontent.com/65232792/267598644-993e516e-a981-4ae4-a10c-bc9781a69776.png)

我之前用ACCESS_TOKEN印象中也有问题。我直接用`GITHUB_TOKEN`了。

这是我的配置：

```yaml
 - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          # Git branch where site will be deployed
          target_branch: gh-pages
          # Create incremental commit instead of doing push force
          keep_history: true
          # Build directory to deploy
          build_dir: public
          # Write the given domain name to the CNAME file
          #fqdn: custom.domain.name # optional
          # Prevent Jekyll from building the site
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

参考： https://docs.github.com/en/actions/security-guides/automatic-token-authentication
