### ISSUE TITLE
keep 同步脚本，可能是个 bug，待确认

### ISSUE THREAD

**Issue by Lax** [yihong0618/running_page#87]
https://github.com/yihong0618/running_page/blob/06d308ebc678b47429a5c7806786b8c028022160/scripts/keep_sync.py#L51

```
i["logs"][0]
```

这里好像只获取每天的最后一条记录，如果一天有多条数据，较早的数据被跳过了。
（只看了代码觉得有问题，还没有实测）

**Comment by yihong0618** [comment]
> https://github.com/yihong0618/running_page/blob/06d308ebc678b47429a5c7806786b8c028022160/scripts/keep_sync.py#L51
> 
> ```
> i["logs"][0]
> ```
> 
> 这里好像只获取每天的最后一条记录，如果一天有多条数据，较早的数据被跳过了。
> （只看了代码觉得有问题，还没有实测）

理论没问题，这块获取的不是最后一条。～

**Comment by yihong0618** [comment]
仔细看了下，没问题
https://github.com/yihong0618/running_page/blob/06d308ebc678b47429a5c7806786b8c028022160/scripts/keep_sync.py#L202

这块获取新的 track 的逻辑在这儿。
是用 data.db 判断的。

获取新 gpx 的逻辑在这儿
https://github.com/yihong0618/running_page/blob/06d308ebc678b47429a5c7806786b8c028022160/scripts/keep_sync.py#L141

**Comment by Lax** [comment]
跟 data.db 对比判断的逻辑没问题。

这个逻辑会导致从 keep api 的 json 里读数据时没有读全，漏了一些 track。

从api 返回的 json 结构如下，这里只取了第一条 logs[0].stats.id，漏了后面两条。

```
data:
  records:
    - date: 2月04日
      logs:
        - type: stats
          stats:
            id: 57b479009962c35607c65348_9223370424448641007_rn
        - type: stats
          stats:
            id: 57b479009962c35607c65348_9223370424516957507_rn
        - type: stats
          stats:
            id: 57b479009962c35607c65348_9223370424529356007_rn
    - date: 2月03日
```

那行代码修改后执行了一下，找回了几条记录。
